STATES
q0 q1 q2 q3 q4 q5 q6 q7 q0_new q1_new q2_new q3_new q4_new q5_new 

INITIAL
(and q0 q0_new)

FINAL
q1 q0_new q2_new q3_new q4_new q5_new 

SYMBOLS
x 

VARIABLES
a0 lp a1 a2 xp l N I x ip i 

TRANSITIONS
x q0
(or (and q6
         (= I1 1)
         (= I0 0)
         (= xp1 x1)
         (= xp1 xp0)
         (= xp1 x0)
         (= xp1 a00)
         (= N1 N0)
         (= lp1 l0)
         (= lp1 lp0)
         (= ip1 (+ i1 1))
         (= ip1 (+ i0 1))
         (= l1 lp1)
         (= ip1 ip0)
         (= a01 a10)
         (= a01 a20)
         (<= ip1 (- lp1 1))
         (>= ip1 3)
         (>= N1 lp1))
    (and q4
         (= ip1 1)
         (= I1 1)
         (= i0 0)
         (= i1 0)
         (= I0 0)
         (= xp1 x1)
         (= xp1 xp0)
         (= xp1 x0)
         (= xp1 a10)
         (= xp1 a00)
         (= N1 N0)
         (= lp1 l0)
         (= lp1 lp0)
         (= ip0 1)
         (= a11 a20)
         (= l1 lp1)
         (>= lp1 2)
         (>= N1 lp1))
    (and q7
         (= I1 1)
         (= i1 1)
         (= I0 0)
         (= i0 1)
         (= xp1 a00)
         (= xp1 x0)
         (= xp1 xp0)
         (= xp1 x1)
         (= N1 N0)
         (= lp1 l0)
         (= lp1 lp0)
         (= ip0 2)
         (= ip1 2)
         (= l1 lp1)
         (= a01 a10)
         (= a01 a20)
         (>= lp1 3)
         (>= N1 lp1)))
#
x q2
(or (and q3
         (= N1 N0)
         (= xp1 xp0)
         (= l1 l0)
         (= x1 x0)
         (= lp1 lp0)
         (= I1 (+ i1 1))
         (= a11 a20)
         (= i1 i0)
         (= i1 I0)
         (= ip1 ip0)
         (>= N1 (+ i1 2)))
    (and q1
         (= x1 x0)
         (= l1 l0)
         (= I1 N1)
         (= N1 N0)
         (= xp1 xp0)
         (= lp1 lp0)
         (= N1 (+ I0 1))
         (= i1 i0)
         (= ip1 ip0))
    (and q2
         (= lp1 lp0)
         (= N1 N0)
         (= x1 x0)
         (= xp1 xp0)
         (= l1 l0)
         (= a11 a20)
         (= i1 i0)
         (= I1 (+ I0 1))
         (= ip1 ip0)
         (<= I1 (- N1 1))
         (<= I1 i1)))
#
x q3
(or (and q3
         (= xp1 xp0)
         (= l1 l0)
         (= N1 N0)
         (= lp1 lp0)
         (= x1 x0)
         (= a10 a20)
         (= i1 i0)
         (= I1 (+ I0 1))
         (= ip1 ip0)
         (<= I1 (- l1 1))
         (<= I1 (- N1 1)))
    (and q1
         (= lp1 lp0)
         (= x1 x0)
         (= xp1 xp0)
         (= a10 a20)
         (= l1 l0)
         (= I1 N1)
         (= N1 N0)
         (= N1 (+ I0 1))
         (= i1 i0)
         (= ip1 ip0))
    (and q5
         (= x1 x0)
         (= lp1 lp0)
         (= a10 a20)
         (= I1 l1)
         (= l1 l0)
         (= N1 N0)
         (= xp1 xp0)
         (= l1 (+ I0 1))
         (= i1 i0)
         (= ip1 ip0)
         (<= l1 (- N1 1))))
#
x q4
(or (and q4
         (= a10 a20)
         (= a00 a20)
         (= x1 x0)
         (= xp1 xp0)
         (= l1 l0)
         (= N1 N0)
         (= lp1 lp0)
         (= i1 i0)
         (= I1 (+ I0 1))
         (= ip1 ip0)
         (<= I1 (- l1 1))
         (<= I1 (- N1 1)))
    (and q1
         (= l1 l0)
         (= I1 N1)
         (= N1 N0)
         (= xp1 xp0)
         (= x1 x0)
         (= a10 a20)
         (= a00 a20)
         (= lp1 lp0)
         (= N1 (+ I0 1))
         (= i1 i0)
         (= ip1 ip0))
    (and q5
         (= a10 a20)
         (= a00 a20)
         (= x1 x0)
         (= xp1 xp0)
         (= lp1 lp0)
         (= I1 l1)
         (= l1 l0)
         (= N1 N0)
         (= l1 (+ I0 1))
         (= i1 i0)
         (= ip1 ip0)
         (<= l1 (- N1 1))))
#
x q5
(or (and q1
         (= x1 x0)
         (= xp1 xp0)
         (= I1 N1)
         (= N1 N0)
         (= l1 l0)
         (= lp1 lp0)
         (= N1 (+ I0 1))
         (= i1 i0)
         (= ip1 ip0))
    (and q5
         (= lp1 lp0)
         (= xp1 xp0)
         (= l1 l0)
         (= x1 x0)
         (= N1 N0)
         (= i1 i0)
         (= I1 (+ I0 1))
         (= ip1 ip0)
         (<= I1 (- N1 1))))
#
x q6
(or (and q7
         (= a01 a10)
         (= lp1 lp0)
         (= x1 x0)
         (= l1 l0)
         (= N1 N0)
         (= xp1 xp0)
         (= a01 a20)
         (= I1 i1)
         (= i1 i0)
         (= i1 (+ I0 1))
         (= ip1 ip0)
         (>= N1 (+ i1 1)))
    (and q6
         (= a01 a10)
         (= l1 l0)
         (= lp1 lp0)
         (= x1 x0)
         (= xp1 xp0)
         (= N1 N0)
         (= a01 a20)
         (= i1 i0)
         (= I1 (+ I0 1))
         (= ip1 ip0)
         (<= I1 (- N1 1))
         (<= I1 (- i1 1)))
    (and q1
         (= x1 x0)
         (= lp1 lp0)
         (= I1 N1)
         (= N1 N0)
         (= l1 l0)
         (= xp1 xp0)
         (= N1 (+ I0 1))
         (= i1 i0)
         (= ip1 ip0)))
#
x q7
(or (and q4
         (= lp1 lp0)
         (= x1 x0)
         (= l1 l0)
         (= N1 N0)
         (= xp1 xp0)
         (= I1 (+ i1 1))
         (= a11 a20)
         (= i1 i0)
         (= i1 I0)
         (= ip1 ip0)
         (= a00 a10)
         (>= l1 (+ i1 2))
         (>= N1 (+ i1 2)))
    (and q3
         (= lp1 lp0)
         (= x1 x0)
         (= N1 N0)
         (= l1 l0)
         (= I1 l1)
         (= xp1 xp0)
         (= l1 (+ i1 1))
         (= a11 a20)
         (= l1 (+ I0 1))
         (= l1 (+ i0 1))
         (= ip1 ip0)
         (= a00 a10)
         (<= l1 (- N1 1)))
    (and q2
         (= x1 x0)
         (= lp1 lp0)
         (= N1 N0)
         (= l1 l0)
         (= I1 l1)
         (= xp1 xp0)
         (= a11 a20)
         (= l1 (+ I0 1))
         (= i1 i0)
         (= ip1 ip0)
         (= a00 a10)
         (<= l1 (- N1 1))
         (<= l1 i1))
    (and q1
         (= xp1 xp0)
         (= I1 N1)
         (= N1 N0)
         (= x1 x0)
         (= lp1 lp0)
         (= l1 l0)
         (= N1 (+ I0 1))
         (= i1 i0)
         (= ip1 ip0)
         (= a00 a10))
    (and q7
         (= lp1 lp0)
         (= xp1 xp0)
         (= N1 N0)
         (= l1 l0)
         (= x1 x0)
         (= a11 a20)
         (= i1 i0)
         (= I1 (+ I0 1))
         (= ip1 ip0)
         (= a00 a10)
         (<= I1 (- N1 1))
         (<= I1 (- l1 1))
         (<= I1 i1)))
#
x q0_new
(let ((a!1 (or q4_new
               (not (= I1 1))
               (not (= I0 0))
               (not (= l1 l0))
               (not (= lp1 lp0))
               (not (= N1 N0))
               (not (= x1 x0))
               (not (= xp1 a00))
               (not (= xp1 xp0))
               (not (= i1 i0))
               (not (= ip1 ip0))
               (not (= a01 a20))
               (not (<= ip1 (- lp1 1)))
               (not (>= N1 2))
               (not (>= ip1 2))))
      (a!2 (or q1_new
               (not (= I1 1))
               (not (= N0 1))
               (not (= I0 0))
               (not (= l1 l0))
               (not (= x1 x0))
               (not (= xp1 a00))
               (not (= xp1 xp0))
               (not (= N1 1))
               (not (= lp1 lp0))
               (not (= i1 i0))
               (not (= ip1 ip0))
               (not (<= ip1 (- lp1 1)))
               (not (>= ip1 1))))
      (a!3 (or q1_new
               (not (= N0 1))
               (not (= I1 1))
               (not (= I0 0))
               (not (= l1 l0))
               (not (= xp1 a00))
               (not (= xp1 xp0))
               (not (= x1 x0))
               (not (= lp1 lp0))
               (not (= N1 1))
               (not (= i1 i0))
               (not (= ip1 ip0))
               (not (<= ip1 (- lp1 1)))
               (not (<= lp1 0))))
      (a!4 (or q3_new
               (not (= I1 1))
               (not (= I0 0))
               (not (= l1 l0))
               (not (= N1 N0))
               (not (= x1 x0))
               (not (= xp1 xp0))
               (not (= xp1 a00))
               (not (= lp1 lp0))
               (not (= i1 i0))
               (not (= ip1 ip0))
               (not (>= N1 2))
               (not (<= ip1 (- lp1 1)))
               (not (<= lp1 0)))))
  (and a!1
       (or q5_new
           (not (= I1 1))
           (not (= I0 0))
           (not (= l1 l0))
           (not (= N1 N0))
           (not (= xp1 a00))
           (not (= xp1 xp0))
           (not (= x1 x0))
           (not (= lp1 lp0))
           (not (= xp1 a20))
           (not (= i1 i0))
           (not (= ip1 ip0))
           (not (<= ip1 0))
           (not (>= N1 2))
           (not (>= lp1 2)))
       (or q1_new
           (not (= I1 1))
           (not (= N0 1))
           (not (= I0 0))
           (not (= l1 l0))
           (not (= lp1 lp0))
           (not (= N1 1))
           (not (= xp1 a00))
           (not (= xp1 xp0))
           (not (= x1 x0))
           (not (= xp1 a20))
           (not (= i1 i0))
           (not (= ip1 ip0))
           (not (<= ip1 0))
           (not (>= lp1 1)))
       (or q3_new
           (not (= I1 1))
           (not (= I0 0))
           (not (= l1 l0))
           (not (= x1 x0))
           (not (= lp1 lp0))
           (not (= N1 N0))
           (not (= xp1 xp0))
           (not (= xp1 a00))
           (not (= i1 i0))
           (not (= ip1 ip0))
           (not (<= ip1 0))
           (not (>= ip1 lp1))
           (not (>= N1 2)))
       a!2
       (or q3_new
           (not (= lp0 1))
           (not (= I1 1))
           (not (= I0 0))
           (not (= N1 N0))
           (not (= lp1 1))
           (not (= xp1 a00))
           (not (= xp1 xp0))
           (not (= l1 l0))
           (not (= x1 x0))
           (not (= xp1 a20))
           (not (= i1 i0))
           (not (= ip1 ip0))
           (not (<= ip1 0))
           (not (>= N1 2)))
       a!3
       (or q3_new
           (not (= I1 1))
           (not (= ip1 1))
           (not (= I0 0))
           (not (= ip0 1))
           (not (= N1 N0))
           (not (= xp1 a00))
           (not (= xp1 xp0))
           (not (= lp1 lp0))
           (not (= l1 l0))
           (not (= x1 x0))
           (not (= i1 i0))
           (not (= a01 a20))
           (not (>= N1 2))
           (not (<= lp1 1)))
       (or q2_new
           (not (= I1 1))
           (not (= I0 0))
           (not (= x1 x0))
           (not (= xp1 xp0))
           (not (= xp1 a00))
           (not (= l1 l0))
           (not (= N1 N0))
           (not (= lp1 lp0))
           (not (= a01 a20))
           (not (= i1 i0))
           (not (= ip1 ip0))
           (not (>= ip1 lp1))
           (not (>= N1 2))
           (not (>= ip1 2)))
       a!4
       (or q1_new
           (not (= I1 1))
           (not (= N0 1))
           (not (= I0 0))
           (not (= x1 x0))
           (not (= N1 1))
           (not (= xp1 xp0))
           (not (= xp1 a00))
           (not (= lp1 lp0))
           (not (= l1 l0))
           (not (= i1 i0))
           (not (= ip1 ip0))
           (not (>= ip1 lp1)))
       (or q5_new
           (not (= ip1 1))
           (not (= I1 1))
           (not (= I0 0))
           (not (= ip0 1))
           (not (= xp1 a00))
           (not (= xp1 xp0))
           (not (= x1 x0))
           (not (= l1 l0))
           (not (= N1 N0))
           (not (= lp1 lp0))
           (not (= i1 i0))
           (not (= a01 a20))
           (not (>= lp1 2))
           (not (>= N1 2)))))
#
x q1_new
(not false)
#
x q2_new
(let ((a!1 (or q3_new
               (not (= xp1 xp0))
               (not (= l1 l0))
               (not (= lp1 lp0))
               (not (= x1 x0))
               (not (= N1 N0))
               (not (= a01 a20))
               (not (= I1 ip1))
               (not (= i1 i0))
               (not (= ip1 (+ I0 1)))
               (not (= ip1 ip0))
               (not (>= N1 (+ ip1 1)))))
      (a!2 (or q2_new
               (not (= l1 l0))
               (not (= xp1 xp0))
               (not (= lp1 lp0))
               (not (= x1 x0))
               (not (= N1 N0))
               (not (= a01 a20))
               (not (= i1 i0))
               (not (= I1 (+ I0 1)))
               (not (= ip1 ip0))
               (not (<= I1 (- N1 1)))
               (not (<= I1 (- ip1 1)))))
      (a!3 (or q1_new
               (not (= xp1 xp0))
               (not (= l1 l0))
               (not (= I1 N1))
               (not (= N1 N0))
               (not (= x1 x0))
               (not (= lp1 lp0))
               (not (= N1 (+ I0 1)))
               (not (= i1 i0))
               (not (= ip1 ip0)))))
  (and a!1 a!2 a!3))
#
x q3_new
(let ((a!1 (or q1_new
               (not (= x1 x0))
               (not (= l1 l0))
               (not (= xp1 xp0))
               (not (= I1 N1))
               (not (= N1 N0))
               (not (= lp1 lp0))
               (not (= N1 (+ I0 1)))
               (not (= i1 i0))
               (not (= ip1 ip0))))
      (a!2 (or q3_new
               (not (= l1 l0))
               (not (= xp1 xp0))
               (not (= N1 N0))
               (not (= lp1 lp0))
               (not (= x1 x0))
               (not (= i1 i0))
               (not (= I1 (+ I0 1)))
               (not (= ip1 ip0))
               (not (<= I1 (- N1 1))))))
  (and a!1 a!2))
#
x q4_new
(let ((a!1 (or q1_new
               (not (= I1 N1))
               (not (= N1 N0))
               (not (= lp1 lp0))
               (not (= l1 l0))
               (not (= xp1 xp0))
               (not (= x1 x0))
               (not (= N1 (+ I0 1)))
               (not (= i1 i0))
               (not (= ip1 ip0))))
      (a!2 (or q5_new
               (not (= x1 x0))
               (not (= lp1 lp0))
               (not (= l1 l0))
               (not (= N1 N0))
               (not (= xp1 xp0))
               (not (= a01 a20))
               (not (= I1 ip1))
               (not (= i1 i0))
               (not (= ip1 (+ I0 1)))
               (not (= ip1 ip0))
               (not (>= N1 (+ ip1 1)))))
      (a!3 (or q4_new
               (not (= lp1 lp0))
               (not (= l1 l0))
               (not (= x1 x0))
               (not (= N1 N0))
               (not (= xp1 xp0))
               (not (= a01 a20))
               (not (= i1 i0))
               (not (= I1 (+ I0 1)))
               (not (= ip1 ip0))
               (not (<= I1 (- N1 1)))
               (not (<= I1 (- ip1 1))))))
  (and a!1 a!2 a!3))
#
x q5_new
(let ((a!1 (or q3_new
               (not (= a00 a20))
               (not (= l1 l0))
               (not (= x1 x0))
               (not (= xp1 xp0))
               (not (= I1 lp1))
               (not (= lp1 lp0))
               (not (= N1 N0))
               (not (= lp1 (+ I0 1)))
               (not (= i1 i0))
               (not (= ip1 ip0))
               (not (>= N1 (+ lp1 1)))))
      (a!2 (or q5_new
               (not (= a00 a20))
               (not (= xp1 xp0))
               (not (= l1 l0))
               (not (= lp1 lp0))
               (not (= N1 N0))
               (not (= x1 x0))
               (not (= i1 i0))
               (not (= I1 (+ I0 1)))
               (not (= ip1 ip0))
               (not (<= I1 (- lp1 1)))
               (not (<= I1 (- N1 1)))))
      (a!3 (or q1_new
               (not (= a00 a20))
               (not (= l1 l0))
               (not (= I1 N1))
               (not (= N1 N0))
               (not (= x1 x0))
               (not (= lp1 lp0))
               (not (= xp1 xp0))
               (not (= N1 (+ I0 1)))
               (not (= i1 i0))
               (not (= ip1 ip0)))))
  (and a!1 a!2 a!3))
#

