#!/bin/bash
java -jar JAltImact.jar examples/simple1.ada -MATHSAT5 -mode1
echo
echo
echo "Press anykey to continue..."
read
java -jar JAltImact.jar examples/simple2.ada -MATHSAT5 -mode1
echo
echo
echo "Press anykey to continue..."
read
java -jar JAltImact.jar examples/simple3.ada -MATHSAT5 -mode1
echo
echo
echo "Press anykey to continue..."
read
java -jar JAltImact.jar examples/array_shift.ada -MATHSAT5 -mode1
echo
echo
echo "Press anykey to continue..."
read
java -jar JAltImact.jar examples/array_simple.ada -MATHSAT5 -mode1
echo
echo
echo "Press anykey to continue..."
read
java -jar JAltImact.jar examples/array_rotation1.ada -MATHSAT5 -mode1
echo
echo
echo "Press anykey to continue..."
read
java -jar JAltImact.jar examples/abp.ada -MATHSAT5 -mode2
echo
echo
echo "Press anykey to continue..."
read
java -jar JAltImact.jar examples/train.ada -MATHSAT5 -mode1
echo
echo
echo "Press anykey to continue..."
read
java -jar JAltImact.jar examples/hw1.ada -MATHSAT5 -mode1
echo
echo
echo "Press anykey to continue..."
read
java -jar JAltImact.jar examples/hw2.ada -MATHSAT5 -mode1
echo
echo
echo "Press anykey to continue..."
read
